### ISSUE TITLE
I created a custom component using this backpack

### ISSUE THREAD

**Issue by addd45** [JAAlperin/esphome-adafruit-7-segment-LED-backpack-example#1]
Not an issue, but if anyone stumbles upon this looking for a way to update this 7 segment display through an 'official' component. I can share my specific example. I'm using a home assistant service (via esphome integration) to update the numerical values.

**Comment by jpduhen** [comment]
@addd45 could you please share? I tried this YAML, but I get a compile error:

`Compiling /data/ht16k33-klok/.pioenvs/ht16k33-klok/libc68/Adafruit GFX Library/Adafruit_GrayOLED.cpp.o
In file included from /data/ht16k33-klok/.piolibdeps/ht16k33-klok/Adafruit GFX Library/Adafruit_GrayOLED.cpp:20:0:
/data/ht16k33-klok/.piolibdeps/ht16k33-klok/Adafruit GFX Library/Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

****************************************************************************
* Looking for Adafruit_I2CDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Adafruit_I2CDevice.h"
* Web  > https://platformio.org/lib/search?query=header:Adafruit_I2CDevice.h
*
****************************************************************************

 #include <Adafruit_I2CDevice.h>
                                ^
compilation terminated.
Archiving /data/ht16k33-klok/.pioenvs/ht16k33-klok/lib768/libESPAsyncWebServer-esphome.a
Compiling /data/ht16k33-klok/.pioenvs/ht16k33-klok/lib0d3/ESP8266mDNS/ESP8266mDNS_Legacy.cpp.o
*** [/data/ht16k33-klok/.pioenvs/ht16k33-klok/libc68/Adafruit GFX Library/Adafruit_GrayOLED.cpp.o] Error 1
Compiling /data/ht16k33-klok/.pioenvs/ht16k33-klok/lib0d3/ESP8266mDNS/LEAmDNS.cpp.o
========================== [FAILED] Took 3.39 seconds ==========================`

**Comment by khobbits** [comment]
```
esphome:
  includes: 
    - Adafruit_LED_Backpack/Adafruit_LEDBackpack.h #https://github.com/adafruit/Adafruit_LED_Backpack 
    - Adafruit_LED_Backpack/Adafruit_LEDBackpack.cpp #https://github.com/adafruit/Adafruit_LED_Backpack 
  libraries:    
    - "SPI"
    - "Wire"
    - "Adafruit BusIO"
    - "Adafruit GFX Library"
```

**Comment by eifachtimon** [comment]
@addd45 I‘m very interested in your custom componement integration and would greatly appreciate your example!

**Comment by addd45** [comment]
Sorry all forgot I posted on this :) 

So I'm using home assistant and esphome and exposing those services. If you don't know about these definitely check them out, they are home automation must haves.
My little project goal is to use these 7seg displays as a scoreboard for my NHL team stl blues, and so the code you will see is designed around that. It's really not too complicated as it uses the `custom_component` api esphome offers. However, they have unfortunately deprecated this now and the docs appear to be removed in favor of external components. [This repo gives examples](https://github.com/thegroove/esphome-custom-component-examples) and may be the best source of documentation left (besides google) :).

Anyway, once you have these setup, here is an example of my esphome setup. its uses 2 7seg displays

```yaml
esphome:
  name: my-name
  includes: 
    - MyBig7SegDisplay.h
    - MySmall7SegDisplay.h
  libraries:
    - "adafruit/Adafruit LED Backpack Library@^1.3.2"
    - "Adafruit GFX Library@^1.10.13"
    - "adafruit/Adafruit BusIO@^1.11.0" 
  platformio_options:
    lib_ldf_mode: deep
esp8266:
  board: nodemcuv2
  framework:
    version: latest
    platform_version: 3.2.0  
mqtt:
  #redacted

# Enable logging
logger:
  level: DEBUG
  
debug:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false

switch: # controls the LED on the nodemcu8266
  - platform: gpio
    name: "Board LED"
    pin:
      number: D0
      inverted: yes

# This is the big 7seg (MyBig7SegDisplay.h)
i2c:
  sda: 4  # data  = D2 = GPIO4
  scl: 5  # clock = D1 = GPIO5
  scan: False # Adafruit uses 0x70
  
#This is the small one (MySmall7SegDisplay.h)
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

#These are the custom components I made, in the cpp code
custom_component:
- lambda: |-
    auto my_big7seg = new MyBig7SegDisplay();
    return {my_big7seg};
- lambda: |-
    auto my_small7seg = new MySmall7SegDisplay();
    return {my_small7seg};  
```

MyBig7SegDisplay.h:

```c
#include "esphome.h"
#include <Adafruit_GFX.h>
#include "Adafruit_LEDBackpack.h"

class MyBig7SegDisplay : public Component, public CustomAPIDevice {

  Adafruit_7segment matrix;

 public:
  void setup() override {
	ESP_LOGD("custom", "Big7Seg Display setup.");
    matrix = Adafruit_7segment();
    matrix.begin(0x70);	
	ResetDisplay();
	
	  // Declare a  service "update_scoreboard"
    //  - Service will be called "esphome.<NODE_NAME>_update_scoreboard" in Home Assistant.
    //  - The service has two arguments (type inferred from method definition):
    //     - blues score: int
    //     - away score: int
    //  - The function on_hello_world declared below will attached to the service.
    register_service(&MyBig7SegDisplay::on_update_scoreboard, "update_scoreboard",
                     {"blues_score", "away_score"});			
	register_service(&MyBig7SegDisplay::on_set_digits, "set_digits",
	                 {"digits"});			
	register_service(&MyBig7SegDisplay::on_power_display, "power_display",
                     {"power_status"});
	register_service(&MyBig7SegDisplay::on_blink_display, "blink_display",
                     {"rate"});
	register_service(&MyBig7SegDisplay::on_set_brightness, "set_brightness",
                     {"brightness"});				
	register_service(&MyBig7SegDisplay::on_set_colon, "set_colon",
					 {"colon_status"});
  }
  void loop() override {
    // This will be called very often after setup time.
    // think of it as the loop() call in Arduino
    
  }
  
  void BlinkDisplay(int rate){
    if (rate >= 0 && rate < 4) //rate can only be 0(not blinking) to 4
    {
	  matrix.blinkRate(rate);
	}
  }
  
  void SetBrightness(int brightness){
    if (brightness >= 0 && brightness < 15) //brightness can only be 0 to 15
    {
	  matrix.setBrightness(brightness);
	}  
  }
  
  void UpdateDisplay(int blues, int opp) {
	/*
	  Scoreboard assumes Blues always the left 2 segments
	  And away team right 2 segments
	*/
	//Do math to format our scoreboard value
	int value = (blues * 100) + opp;

	ESP_LOGD("custom", "Writing value '%u' to big 7Seg.", value);

	matrix.print(value, DEC);
	
	//middle 0
	if (opp < 10){
	  matrix.writeDigitRaw(3, 0x00);
	}
    
    matrix.writeDisplay();
	delay(50);
  }
  
  void on_blink_display(int rate){
    ESP_LOGD("custom", "Updating Blues Scoreboard blink rate. rate=%u", rate);
    BlinkDisplay(rate);
  }
  
  void on_set_brightness(int brightness){
    ESP_LOGD("custom", "Updating Blues Scoreboard brightness. level=%u", brightness);
    SetBrightness(brightness);
  }
  
  void SetDigits(int digits){
	if (digits > 9999){
	  ESP_LOGD("error", "Error Updating Blues Scoreboard digits. value too large");
	  return;
	}
    matrix.print(digits, DEC);
	
	matrix.writeDisplay();
	delay(100);
  }

  void on_set_digits(int digits){
    ESP_LOGD("custom", "Updating Blues Scoreboard digits. digits: %u", digits);
	SetDigits(digits);
  }

  
  void SetColon(bool colonStatus) {
	matrix.drawColon(colonStatus);
    matrix.writeDisplay();
    delay(10);
  }
  
  void on_update_scoreboard(int blues_score, int away_score) {
    ESP_LOGD("custom", "Updating Blues Scoreboard. blues=%u | others=%u", blues_score, away_score);
    UpdateDisplay(blues_score, away_score);
  }
  
  void on_set_colon(bool colon_status){
    ESP_LOGD("custom", "Setting Colon State");
	SetColon(colon_status);  
  }
    
  void on_power_display(bool power_status){
    ESP_LOGD("custom", "Powering display '%b'", power_status);
    PowerDisplay(power_status);
  }
	
  void ResetDisplay(){
    ESP_LOGD("custom", "Resetting Blues Scoreboard.");
  //Display 6969 on the big display (lol)
    matrix.print(6969, DEC);
    matrix.writeDisplay();
	delay(500);
  }
  
  void PowerDisplay(bool on) {
	//Turn on displays
	if (on) {
      ResetDisplay();
	}
	//Turn off displays
	else {
    //Turn off big 7seg by writing 0x00 to each segment
      for(int i=0; i< 5; i++){
        matrix.writeDigitRaw(i, 0x00);
        matrix.writeDisplay();    
		delay(500);
      }
	}  
  }
};
```

And MySmall7SegDisplay.h

```c
#include "esphome.h"
#include <Wire.h>
#include <SPI.h>
#define CS_PIN 10
#define SPI_CLEAR 0x76

class MySmall7SegDisplay : public Component, public CustomAPIDevice {

 public:
  void setup() override {
    ESP_LOGD("custom", "Small 7seg Display setup.");

    pinMode(CS_PIN, OUTPUT);
    digitalWrite(CS_PIN, HIGH); //By default, don't be selecting OpenSegment
    SPI.begin(); //Start the SPI hardware
    SPI.setClockDivider(SPI_CLOCK_DIV64); //Slow down the master a bit
    digitalWrite(CS_PIN, LOW); //Drive the CS pin low to select OpenSegment
    ResetDisplay();
	
    register_service(&MySmall7SegDisplay::on_update_sog, "update_sog",
                     {"blues_sog", "away_sog"});
					 
	register_service(&MySmall7SegDisplay::on_power_small_display, "power_small_display",
                     {"power_status"});
  }
  void loop() override {
    // This will be called very often after setup time.
    // think of it as the loop() call in Arduino
    
  }
  
  void UpdateDisplay(int blues, int opp) {
	/*
	  SOG assumes Blues always the left 2 segments
	  And away team right 2 segments
	*/
	//Do math to format our SOG value
	int value = (blues * 100) + opp;

	ESP_LOGD("custom", "Writing value '%u' to little 7Seg.", value);
	spiSendValue(value);
  }
					 
  void on_update_sog(int blues_sog, int away_sog) {
    ESP_LOGD("custom", "Updating Blues SOG. blues=%u | others=%u", blues_sog, away_sog);
    UpdateDisplay(blues_sog, away_sog);
  }
    
  void on_power_small_display(bool power_status){
    ESP_LOGD("custom", "Powering little display '%u'", power_status);
    PowerSmallDisplay(power_status);
  }
	
  //Given a number, spiSendValue chops up an integer into four values and sends them out over spi
  void spiSendValue(int tempCycles)
  {
  	digitalWrite(CS_PIN, LOW); //Drive the CS pin low to select OpenSegment
  
  	SPI.transfer(tempCycles / 1000); //Send the left most digit
  	tempCycles %= 1000; //Now remove the left most digit from the number we want to display
  	SPI.transfer(tempCycles / 100);
  	tempCycles %= 100;
  	SPI.transfer(tempCycles / 10);
  	tempCycles %= 10;
  	SPI.transfer(tempCycles); //Send the right most digit
  
  	digitalWrite(CS_PIN, HIGH); //Release the CS pin to de-select OpenSegment
  }	
  
  void ResetDisplay(){
    ESP_LOGD("custom", "Resetting Blues SOG board.");
	
	//Display 'HUSS' on little 7 seg
    SPI.transfer(SPI_CLEAR); //clear display (also 'v')
    SPI.transfer(0x48);  //H
    SPI.transfer(0x55);  //U
    SPI.transfer(0x53);  //S
    SPI.transfer(0x53);  //S
    SPI.transfer(0x79); // Send the Move Cursor Command
    SPI.transfer(0x00); // Set cursor to first digit    
  }
  
  void PowerSmallDisplay(bool on) {
	//Turn on displays
	if (on) {
      ResetDisplay();
	}
	//Turn off displays
	else {
      //Turn off small 7seg by sending a clear byte
      SPI.transfer(SPI_CLEAR);       
    }
  }  
  
};

```


Hopefully this is enough to get going. I can add more detail if anything is needed
